# Usa la imagen oficial de Node como imagen base
FROM node:17-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos necesarios para instalar las dependencias
COPY package.json .

# Instala las dependencias de la aplicación
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

EXPOSE 8080

# Comando para iniciar la aplicación en producción
CMD ["npm", "run", "dev"]